### ISSUE TITLE
SIGSEGV when using exec::sequence and exec::task

### ISSUE THREAD

**Issue by kyusic** [NVIDIA/stdexec#1418]
The following code which uses exec::sequence fails to run receiving SIGSEGV signal:

```cpp
    auto make_task = []() -> exec::task<void> {
      co_return;
    };
    stdexec::sync_wait(exec::sequence(stdexec::just(), make_task()));
```

If compiled and run with address sanitizer, it would give the following error(on Apple clang version 16.0.0):

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==96569==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7bfda9be4ff4 bp 0x00016bdc46b0 sp 0x00016bdc4680 T0)
==96569==The signal is caused by a READ memory access.
==96569==Hint: address points to the zero page.
    #0 0x7bfda9be4ff4  (<unknown module>)
    #1 0x1045dd488 in stdexec::__connect_awaitable_::__operation_base::start() & __connect_awaitable.hpp:85
    #2 0x1046fa36c in void exec::_seq::_rcvr<stdexec::__sexpr<stdexec::(anonymous namespace)::'lambda8'(){}, stdexec::(anonymous namespace)::__anon>, exec::__task::basic_task<void, exec::__task::__default_task_context_impl<(exec::__task::__scheduler_affinity)1>>, stdexec::__sync_wait::__receiver<>::__t>::set_value<>() && sequence.hpp:79
    #3 0x1046f9fec in auto void stdexec::__just::__impl<stdexec::__just::just_t>::start::'lambda'<typename $T, typename $T0>($T&, $T0&)::operator()<stdexec::__tup::__tuple<(stdexec::__pack::__t<>*)0>, exec::_seq::_rcvr<stdexec::__sexpr<stdexec::(anonymous namespace)::'lambda8'(){}, stdexec::__sexpr::__anon>, stdexec::__tup::__tuple<(stdexec::__pack::__t<>*)0>::__task::basic_task<void, stdexec::__sexpr<stdexec::(anonymous namespace)::'lambda8'(){}, stdexec::__sexpr::__anon>::__default_task_context_impl<(stdexec::__sexpr<stdexec::(anonymous namespace)::'lambda8'(){}, stdexec::__sexpr::__anon>::__scheduler_affinity)1>>, stdexec::__sync_wait::__receiver<>::__t>>($T, $T0) const::'lambda'<typename ...$T1>($T1&...)::operator()<>($T1&) const __just.hpp:47
    #4 0x1046f9dc0 in void stdexec::__just::__impl<stdexec::__just::just_t>::start::'lambda'<typename $T, typename $T0>($T&, $T0&)::operator()<stdexec::__tup::__tuple<(stdexec::__pack::__t<>*)0>, exec::_seq::_rcvr<stdexec::__sexpr<stdexec::(anonymous namespace)::'lambda8'(){}, stdexec::__sexpr::__anon>, stdexec::__tup::__tuple<(stdexec::__pack::__t<>*)0>::__task::basic_task<void, stdexec::__sexpr<stdexec::(anonymous namespace)::'lambda8'(){}, stdexec::__sexpr::__anon>::__default_task_context_impl<(stdexec::__sexpr<stdexec::(anonymous namespace)::'lambda8'(){}, stdexec::__sexpr::__anon>::__scheduler_affinity)1>>, stdexec::__sync_wait::__receiver<>::__t>>($T, $T0) const __just.hpp:45
    #5 0x1046f9c3c in auto stdexec::__detail::__op_state<stdexec::__sexpr<stdexec::(anonymous namespace)::'lambda8'(){}, stdexec::(anonymous namespace)::__anon>, exec::_seq::_rcvr<stdexec::__sexpr<stdexec::(anonymous namespace)::'lambda8'(){}, stdexec::(anonymous namespace)::__anon>, exec::__task::basic_task<void, exec::__task::__default_task_context_impl<(exec::__task::__scheduler_affinity)1>>, stdexec::__sync_wait::__receiver<>::__t>>::start() &::'lambda'(auto&...)::operator()<>(auto&...) const __basic_sender.hpp:414
    #6 0x1046f9af8 in exec::_seq::_opstate<stdexec::__sync_wait::__receiver<>::__t, stdexec::__sexpr<stdexec::(anonymous namespace)::'lambda8'(){}, stdexec::(anonymous namespace)::__anon>, exec::__task::basic_task<void, exec::__task::__default_task_context_impl<(exec::__task::__scheduler_affinity)1>>>::start() & sequence.hpp:141
    #7 0x1046f5e94 in _ZNK7stdexec11__sync_wait11sync_wait_t12apply_senderIN4exec4_seq5_sndrIJNS_7__sexprIXtlNS_12_GLOBAL__N_1UlvE8_EEENS7_6__anonEEENS3_6__task10basic_taskIvNSB_27__default_task_context_implILNSB_20__scheduler_affinityE1EEEEEEEEEENSt3__18optionalINS_3__iIXL_ZNS_3_OkIJT_NS_4__qqINSI_5tupleEEEEEEEELb1EE3__fINS_12__mtry_catchINS_12__mtry_eval_INS0_23__sync_wait_result_implEEENS_22_WITH_META_FUNCTION_T_ISU_EEEEE3__fISM_SP_EEEEOSM_ __sync_wait.hpp:268
    #8 0x1046f4cf0 in std::__1::optional<stdexec::__sync_wait::__value_tuple_for<exec::_seq::_sndr<stdexec::__sexpr<stdexec::(anonymous namespace)::'lambda8'(){}, stdexec::(anonymous namespace)::__anon>, exec::__task::basic_task<void, exec::__task::__default_task_context_impl<(exec::__task::__scheduler_affinity)1>>>>::__t> stdexec::__sync_wait::sync_wait_t::operator()<exec::_seq::_sndr<stdexec::__sexpr<stdexec::(anonymous namespace)::'lambda8'(){}, stdexec::(anonymous namespace)::__anon>, exec::__task::basic_task<void, exec::__task::__default_task_context_impl<(exec::__task::__scheduler_affinity)1>>>>(exec::_seq::_sndr<stdexec::__sexpr<stdexec::(anonymous namespace)::'lambda8'(){}, stdexec::(anonymous namespace)::__anon>, exec::__task::basic_task<void, exec::__task::__default_task_context_impl<(exec::__task::__scheduler_affinity)1>>>&&) const __sync_wait.hpp:215
...
```

**Comment by ericniebler** [comment]
@kyusic thanks for the report. does #1424 fix your problem?

**Comment by kyusic** [comment]
> [@kyusic](https://github.com/kyusic) thanks for the report. does [#1424](https://github.com/NVIDIA/stdexec/pull/1424) fix your problem?

Yes it does. Thanks.
